# Generated by Django 4.1.3 on 2022-11-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registros",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("correo", models.CharField(max_length=50)),
                ("materia", models.CharField(max_length=50)),
            ],
        ),
    ]
